

server {
  listen 8080 default_server;
  client_max_body_size 5G;

  access_log /var/log/nginx/wordpress.access.log;
  error_log /var/log/nginx/wordpress.error.log;
  
  root /var/www/html/wordpress;

  # Index directive
  index index.php index.html index.htm;

  # location ~ \.php$ {
  #   fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
  #   fastcgi_index index.php;
  #   fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
  #   include fastcgi_params;
  #   fastcgi_read_timeout 600;
  # }

  location ~ \.php$ {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    if (!-f $document_root$fastcgi_script_name) {
        return 404;
    }
    fastcgi_keep_conn on;
    fastcgi_pass   unix:/var/run/php/php8.1-fpm.sock;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;

    include fastcgi_params;
  }

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

}